### ISSUE TITLE
Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by mruiter** [athombv/node-homey-zwavedriver#31]
Error: Cannot find module 'async'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:5:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

**Comment by caseda** [comment]
`npm install --save async` 😃

**Comment by mruiter** [comment]
Ahhh, new instructions ;) .......
